name: Los Jaweros
favicon: null
layout_spectrum: 0.22914432967081666
typography_spectrum: 0.32649803487583995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#54575e'
    - '#ffffff'
    - '#161616'
    - '#e53037'
    - '#949aa6'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.27147684106603265
  rhythmicContrast: 0.75
purpose: []
