name: Los Jaweros
favicon: null
layout_spectrum: 0
typography_spectrum: 0.20927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#54575e'
    - '#ffffff'
    - '#161616'
    - '#e53037'
    - '#949aa6'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
