name: Los Jaweros
favicon: null
layout_spectrum: 0.22914432967081666
typography_spectrum: 0.32649803487583995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05786723061464727
  lightness: 0.39109444944188
  saturation: 0.27147684106603265
  rhythmicContrast: 0.6642030929215252
purpose: []
